#!/bin/sh
[ "$ACTION" = "ifup" ] || [ "$ACTION" = "update" ] || exit 0
[ "$INTERFACE" = "loopback" ] && exit 0

[ -d /sys/kernel/debug/hnat ] || modprobe mtkhnat 2>/dev/null
[ -d /sys/kernel/debug/hnat ] || exit 0

/usr/bin/ucode /usr/share/ucode/hnat/detect.uc
